---
label: Spelling Bee Assistant
title: Assistant
url: https://{{name}}.app/
domain: '{{name}}.app'
repo: draber/draber.github.io.git
targetUrl: '{{nyt}}/puzzles/spelling-bee'
twitter: "@d_raber"
ns: sba
nyt: https://www.nytimes.com
kofi:
  url: https://ko-fi.com/sbassistant
  text: Buy me a coffee
rollup:
  input: src/app/main.js
  format: iife
  uncompressed: assets/js/{{name}}.js
  compressed: assets/js/{{name}}.min.js
 
extension:
  templates:
    manifest: src/templates/extension/manifest.json
    content: src/templates/extension/content.js
    readme: src/templates/{{ns}}/readme.md
    assets: src/templates/extension/assets
    sba: '{{name}}.js'
    sba-min: '{{name}}.min.js'
  stores:
    chrome:
      url: https://chrome.google.com/webstore/detail/{{name}}/ncejlmlagglodbdmkfmgnadfnbhnjcpg
      manifest:
        manifest_version: 3
        host_permissions:
          - '{{nyt}}/*'
        # web_accessible_resources:
        #   - resources:
        #       - '{{name}}.js'
        #     matches:
        #       - '{{nyt}}/*'
    # firefox:
    #   url: https://addons.mozilla.org/en-US/firefox/addon/{{name}}/
    #   enforce_unminified: true
    #   manifest:
    #     # permissions:
    #     #   - '{{nyt}}/*'
    #     browser_specific_settings:
    #       gecko:
    #         id: '{4474f7b5-4da5-4332-8847-074f35456496}'
    #         strict_min_version: 68.0
    # microsoft:
    #   url: https://microsoftedge.microsoft.com/addons/detail/{{name}}/doeniefjeejkkdfnakoflmjlmfipejin
    #   manifest:
    #     # permissions:
    #     #   - '{{nyt}}/*'
    opera:
      url: https://addons.opera.com/en/extensions/details/{{name}}/
      manifest:
        # permissions:
        #   - '{{nyt}}/*'

scss:
  app: src/scss/app.scss
  site: src/scss/site.scss
bookmarklet:
  remote: https://{{name}}.app/assets/js/{{name}}.min.js
  local: assets/js/{{name}}.min.js
  template: src/templates/bookmarklet/template.js
css:
  app: src/css/app.css
