frontend:
    version: version
    label: label
    title: title
    url: url
    ns: ns
    kofi: kofi
    targetUrl: targetUrl
    lsKey: lsKey

extensions:
    name: label
    description: description
    homepage_url: url
    version: version
    icons: extension.icons

bookmarklet:
    remote:   bookmarklet.remote
    local:    bookmarklet.local
    template: bookmarklet.template